git:
  depth: 2
branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - "6.1"
  - "5.11"
  - "5.0"
  - "4.4"
  - "4.0"
  - "0.12"
install:
  - npm install
  - npm install -g gulp
script:
  - gulp lint
  - gulp test
